<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cadastro\Module'                        => __DIR__ . '/Module.php',
    'Cadastro\Controller\IndexController' => __DIR__ . '/src/Cadastro/Controller/IndexController.php',
    'CadastroTest\Framework\TestCase'        => __DIR__ . '/tests/Cadastro/Framework/TestCase.php',
    'CadastroTest\SampleTest'                => __DIR__ . '/tests/Cadastro/SampleTest.php',
);
